before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

dist: trusty
cache: pip
language: python
python:
    - "3.5"
    - "3.6"

# command to install dependencies
install:
    - pip install --upgrade pip setuptools wheel
    - pip install Cython
    - pip install -r requirements.txt --only-binary=numpy,scipy,cvxopt
script:
    - nosetests --with-coverage

after_success:
    - codecov -t CODECOV_TOKEN="bf241da9-a152-4025-baa6-60013f5f2a85"
